name: bmi_calculator
description: A Flutter BMI Calculator app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.3
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.2.3
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  permission_handler: ^11.1.0
  page_transition: ^2.1.0
  provider: ^6.1.2
  timezone: ^0.9.4
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
